# Generated by Django 5.2.1 on 2025-05-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmeserie',
            name='categoria',
            field=models.CharField(choices=[('Filme', 'Filme'), ('Serie', 'Série')], max_length=10),
        ),
    ]
