# Generated by Django 5.2.1 on 2025-05-14 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0002_alter_filmeserie_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usuariofilmeserie',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmes_series_assistidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuariojogo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_adquiridos', to=settings.AUTH_USER_MODEL),
        ),
    ]
